config/routes.rb
Rails.application.routes.draw do
  resources :telefonids
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/telefonid.rb
class Telefonid < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/telefonids_controller.rb
class TelefonidsController < ApplicationController
  before_action :set_telefonid, only: [:show, :edit, :update, :destroy]

  # GET /telefonids
  # GET /telefonids.json
  def index
    @telefonids = Telefonid.all
  end

  # GET /telefonids/1
  # GET /telefonids/1.json
  def show
  end

  # GET /telefonids/new
  def new
    @telefonid = Telefonid.new
  end

  # GET /telefonids/1/edit
  def edit
  end

  # POST /telefonids
  # POST /telefonids.json
  def create
    @telefonid = Telefonid.new(telefonid_params)

    respond_to do |format|
      if @telefonid.save
        format.html { redirect_to @telefonid, notice: 'Telefonid was successfully created.' }
        format.json { render :show, status: :created, location: @telefonid }
      else
        format.html { render :new }
        format.json { render json: @telefonid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefonids/1
  # PATCH/PUT /telefonids/1.json
  def update
    respond_to do |format|
      if @telefonid.update(telefonid_params)
        format.html { redirect_to @telefonid, notice: 'Telefonid was successfully updated.' }
        format.json { render :show, status: :ok, location: @telefonid }
      else
        format.html { render :edit }
        format.json { render json: @telefonid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefonids/1
  # DELETE /telefonids/1.json
  def destroy
    @telefonid.destroy
    respond_to do |format|
      format.html { redirect_to telefonids_url, notice: 'Telefonid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telefonid
      @telefonid = Telefonid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telefonid_params
      params.require(:telefonid).permit(:Nimi, :kirjeldus, :Sisemalu, :Muutmalu, :Protsessor, :Protsessori_kiirus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/telefonids_helper.rb
module TelefonidsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/telefonids/_form.html.erb
<%= form_with(model: telefonid, local: true) do |form| %>
  <% if telefonid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telefonid.errors.count, "error") %> prohibited this telefonid from being saved:</h2>

      <ul>
      <% telefonid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nimi %>
    <%= form.text_field :Nimi %>
  </div>

  <div class="field">
    <%= form.label :kirjeldus %>
    <%= form.text_area :kirjeldus %>
  </div>

  <div class="field">
    <%= form.label :Sisemalu %>
    <%= form.text_field :Sisemalu %>
  </div>

  <div class="field">
    <%= form.label :Muutmalu %>
    <%= form.text_field :Muutmalu %>
  </div>

  <div class="field">
    <%= form.label :Protsessor %>
    <%= form.text_field :Protsessor %>
  </div>

  <div class="field">
    <%= form.label :Protsessori_kiirus %>
    <%= form.text_field :Protsessori_kiirus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/telefonids/edit.html.erb
<h1>Editing Telefonid</h1>

<%= render 'form', telefonid: @telefonid %>

<%= link_to 'Show', @telefonid %> |
<%= link_to 'Back', telefonids_path %>

app/views/telefonids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telefonids</h1>

<table>
  <thead>
    <tr>
      <th>Nimi</th>
      <th>Kirjeldus</th>
      <th>Sisemalu</th>
      <th>Muutmalu</th>
      <th>Protsessor</th>
      <th>Protsessori kiirus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telefonids.each do |telefonid| %>
      <tr>
        <td><%= telefonid.Nimi %></td>
        <td><%= telefonid.kirjeldus %></td>
        <td><%= telefonid.Sisemalu %></td>
        <td><%= telefonid.Muutmalu %></td>
        <td><%= telefonid.Protsessor %></td>
        <td><%= telefonid.Protsessori_kiirus %></td>
        <td><%= link_to 'Show', telefonid %></td>
        <td><%= link_to 'Edit', edit_telefonid_path(telefonid) %></td>
        <td><%= link_to 'Destroy', telefonid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telefonid', new_telefonid_path %>

app/views/telefonids/new.html.erb
<h1>New Telefonid</h1>

<%= render 'form', telefonid: @telefonid %>

<%= link_to 'Back', telefonids_path %>

app/views/telefonids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nimi:</strong>
  <%= @telefonid.Nimi %>
</p>

<p>
  <strong>Kirjeldus:</strong>
  <%= @telefonid.kirjeldus %>
</p>

<p>
  <strong>Sisemalu:</strong>
  <%= @telefonid.Sisemalu %>
</p>

<p>
  <strong>Muutmalu:</strong>
  <%= @telefonid.Muutmalu %>
</p>

<p>
  <strong>Protsessor:</strong>
  <%= @telefonid.Protsessor %>
</p>

<p>
  <strong>Protsessori kiirus:</strong>
  <%= @telefonid.Protsessori_kiirus %>
</p>

<%= link_to 'Edit', edit_telefonid_path(@telefonid) %> |
<%= link_to 'Back', telefonids_path %>